### ISSUE TITLE
h5py issue with new version

### ISSUE THREAD

**Issue by arnaudon** [BlueBrain/morph-tool#48]
I'm getting this  in https://github.com/BlueBrain/morph-tool/pull/47, maybe worth to be fixed in a separate PR?

```  
======================================================================
  ERROR: test_apical_point.test_get_apical_point
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/runner/work/morph-tool/morph-tool/.tox/py36/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
      self.test(*self.arg)
    File "/home/runner/work/morph-tool/morph-tool/tests/test_apical_point.py", line 22, in test_get_apical_point
      morph = Morphology(os.path.join(DATA, 'apical_test.h5'))
  morphio._morphio.RawDataError: Error in HDF5 Group
  h5v2 is no longer supported, see: https://github.com/BlueBrain/MorphIO#H5v2
```

**Comment by wizmer** [comment]
Thanks, I'm on it. I need to convert all h5v2 files to h5v1.

**Comment by arnaudon** [comment]
Ah yes,  this is your latest PR on morphio, I thought this was the new version of h5py haha. Easy then!
